CUDA_VISIBLE_DEVICES=0 bash scripts/process/gen_prefer_next-7b-nohallu.sh /mnt/bn/wxd-video-understanding/wangxd/models/vicuna/LLaVA-NeXT-Video-7B vicuna_v1 16 2 average no_token True /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/dpo_train_data /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/sft_dpo_17k.jsonl 3000 4000 224 &
CUDA_VISIBLE_DEVICES=1 bash scripts/process/gen_prefer_next-7b-nohallu.sh /mnt/bn/wxd-video-understanding/wangxd/models/vicuna/LLaVA-NeXT-Video-7B vicuna_v1 16 2 average no_token True /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/dpo_train_data /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/sft_dpo_17k.jsonl 4000 5000 224 &
CUDA_VISIBLE_DEVICES=2 bash scripts/process/gen_prefer_next-7b-nohallu.sh /mnt/bn/wxd-video-understanding/wangxd/models/vicuna/LLaVA-NeXT-Video-7B vicuna_v1 16 2 average no_token True /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/dpo_train_data /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/sft_dpo_17k.jsonl 5000 6000 224 &


# CUDA_VISIBLE_DEVICES=0 bash scripts/process/gen_prefer_next-7b-nohallu.sh /mnt/bn/wxd-video-understanding/wangxd/models/vicuna/LLaVA-NeXT-Video-7B vicuna_v1 16 2 average no_token True /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/dpo_train_data /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/sft_dpo_17k.jsonl 6000 7000 224 &
# CUDA_VISIBLE_DEVICES=1 bash scripts/process/gen_prefer_next-7b-nohallu.sh /mnt/bn/wxd-video-understanding/wangxd/models/vicuna/LLaVA-NeXT-Video-7B vicuna_v1 16 2 average no_token True /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/dpo_train_data /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/sft_dpo_17k.jsonl 7000 8000 224 &
# CUDA_VISIBLE_DEVICES=2 bash scripts/process/gen_prefer_next-7b-nohallu.sh /mnt/bn/wxd-video-understanding/wangxd/models/vicuna/LLaVA-NeXT-Video-7B vicuna_v1 16 2 average no_token True /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/dpo_train_data /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/sft_dpo_17k.jsonl 8000 9000 224 &
# CUDA_VISIBLE_DEVICES=3 bash scripts/process/gen_prefer_next-7b-nohallu.sh /mnt/bn/wxd-video-understanding/wangxd/models/vicuna/LLaVA-NeXT-Video-7B vicuna_v1 16 2 average no_token True /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/dpo_train_data /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/sft_dpo_17k.jsonl 9000 10000 224 &
# CUDA_VISIBLE_DEVICES=4 bash scripts/process/gen_prefer_next-7b-nohallu.sh /mnt/bn/wxd-video-understanding/wangxd/models/vicuna/LLaVA-NeXT-Video-7B vicuna_v1 16 2 average no_token True /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/dpo_train_data /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/sft_dpo_17k.jsonl 10000 11000 224 &
# CUDA_VISIBLE_DEVICES=5 bash scripts/process/gen_prefer_next-7b-nohallu.sh /mnt/bn/wxd-video-understanding/wangxd/models/vicuna/LLaVA-NeXT-Video-7B vicuna_v1 16 2 average no_token True /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/dpo_train_data /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/sft_dpo_17k.jsonl 11000 12000 224 &
# CUDA_VISIBLE_DEVICES=6 bash scripts/process/gen_prefer_next-7b-nohallu.sh /mnt/bn/wxd-video-understanding/wangxd/models/vicuna/LLaVA-NeXT-Video-7B vicuna_v1 16 2 average no_token True /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/dpo_train_data /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/sft_dpo_17k.jsonl 12000 13000 224 &
# CUDA_VISIBLE_DEVICES=7 bash scripts/process/gen_prefer_next-7b-nohallu.sh /mnt/bn/wxd-video-understanding/wangxd/models/vicuna/LLaVA-NeXT-Video-7B vicuna_v1 16 2 average no_token True /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/dpo_train_data /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/sft_dpo_17k.jsonl 13000 14000 224 &

# CUDA_VISIBLE_DEVICES=0 bash scripts/process/gen_prefer_next-7b-nohallu.sh /mnt/bn/wxd-video-understanding/wangxd/models/vicuna/LLaVA-NeXT-Video-7B vicuna_v1 16 2 average no_token True /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/dpo_train_data /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/sft_dpo_17k.jsonl 14000 15000 224 &
# CUDA_VISIBLE_DEVICES=1 bash scripts/process/gen_prefer_next-7b-nohallu.sh /mnt/bn/wxd-video-understanding/wangxd/models/vicuna/LLaVA-NeXT-Video-7B vicuna_v1 16 2 average no_token True /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/dpo_train_data /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/sft_dpo_17k.jsonl 15000 16000 224 &
# CUDA_VISIBLE_DEVICES=2 bash scripts/process/gen_prefer_next-7b-nohallu.sh /mnt/bn/wxd-video-understanding/wangxd/models/vicuna/LLaVA-NeXT-Video-7B vicuna_v1 16 2 average no_token True /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/dpo_train_data /mnt/bn/wxd-video-understanding/wangxd/data/shareVideoGPTV/sft_dpo_17k.jsonl 16000 17000 224 &
